package actions

import (
	"errors"
	"fmt"
	"github.com/codegangsta/cli"
	"github.com/philippecarle/fuck/foaas"
	"github.com/tcnksm/go-gitconfig"
	"strings"
)

const Chuck  = `.               .......................................................................
.     . .  .          . .  ....   ..    ,=$NNNMN$~.     .  .......................................
. . ............................,NMMMMMMMMMMMMMMMMMMMMMMM?  ......................................
.     . ....       ...     ....MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8     ..............................
.        . .       ..   .  ...MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN................................
. . . . .. .. . .  ...     ...MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM,. ............................
. . . . .. .... .  ...... ...MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM..............................
.   . .    .. .     ..  .  ..MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD ............................
............................. DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.............................
............................. MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.. ..........................
.............................:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM, ...........................
.............................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM ...........................
............................ MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM ...........................
............................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD..     ... ... ..............
............................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM~$MMMMMMMMMMMMMMMMMMM+  .............
...........................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM=. .........
......................... .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN ........
....... ..................MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+ ......
....N:... ..............MMMMMMMMMMMMZ7 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM~ .....
. .. MM+. . .   . .... .,=?$8DMMMMMMMMMMMMMMMMMMMDOZ$III,7IIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM......
. ..  IMMMMMMMMMMMMMMMMMMMMMMMMM8MMMMMMMMMIMMMMM8,. ...........O. =8MMMMMMMMMMMMMMMMMMMMMMMM......
. .. .. +MMMMMMMMMMMMMMMMMMMMMMM ..N. .....~MMMM...............:MMMMNMMMMMMMMMMMMMMMMMMMMMMM. ....
.... . ....8MMMMMMMMMMMMMMMMMMMMM.....:..DMMMMMNZ Z.... .......M$MMMMMMMMMMMMMMMMMMMMMMMMMMM  ....
...   . .. .  ~MMMMMMMMMMN,.MMMMM....... 7=MMMMMMO....Z .......MM7MMMMMMMMMMI.MMMMMMMMMMMMM.......
... . . ....... ... MMMMMMM?.MMMMMMMM  Z...MMMZ .. .,M..,........MMMMMMMMMMMMMMM .+MMMMMMMMM=.......
............. ... ...,MMMM M.......DOM ....N7..................MMMMMMMMMMMMMMMM.....MMMMMM........
... . ....... ..........,M.M....... M. ... .  ... ..............M...$MMMMMMMMM$. ... MMM, ........
. .     .. ..   . .. .  .~  .......... ........~. ..............M..=....+MMMMMMMMM, .~D...........
... ......................,......+.NMI~........ . ..............M.,.I...MMMMMMMMMMMMMM? ..........
. .    ....     . .. .   ..D ....$... ...... O..................,.....$MMMMMMMMMMMM~. ............
. . .     .. .    . .. .   ..$  ..M.......... M M.. .............. 8  .OMMMMMMMMMMMN+OMMMO. ........
. .  .  ..      . .. .   . ~.....=7I,,.,,IMI...M.................. ..MMMMMM....?...,?.............
. ..  . ..      . .. .   . .   . DMMMMMMMMMMMMMMMO..............D...MMMMMMMMM.....................
................. ..... .. . .MMMMMMMMMMMMMMDDMM:,N..............DMMMMMMM~?MM.....................
............................ ZMMMMMNMM8 . .... ...,~............  MMMMMMMMM .. :..................
. .   .           .. .   . .MMMMM,:......::~..M8M8MM...............MMMMM Z D=.....................
. . .     ..      . .  .   . ..MMMM ... . .........,MM..............MMMMMO$.........................
...  . ......  ..... .. .....MMMMM... =.=. .. . . MM ....... . ...MMMMMMM  .......................
.. .................... .......NMMMMMMMMMM?  ..O.?NM7 ....... ......MMMMMM.Z.......................
. . .  .   . .    . .. .   ......NMMMMMMMMMMMMMMMMM........  $ . ...MMMN, M8 .......................
. .     .  ..   . .. .   . .....=MMMMMMMMMMMMMM.........,, ......MMMMMMMM ........................
...  ........ ... .... ... ..... OMMMMMMMM8 , .. .. .,N.... ...:MMMMMMMMMMD, .....................
. . ..    ..        ....   . ....+,..MMMMMMMM?N. ...~MD.:MNI8MMMMMMMMMMMMMMMMMZ ....................
. ..........................  .MMM MM$,MMMMMMMMMMMMM..MMMMMMMMMMMMMMMMMMMMMMMMMM....................
................ .......... NMMMM+ MMMMMMN. .,...MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM. , ...............
..................  .....MMMMMM..OMMMMMMMMM$..MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.MMMZ .............
.. .   .. ,7MMMMMMMM...MMMMMMMM .,:OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...........
. .MMMMMMD?+. MMMMMM ..MMMMMMMMMM.MMMMM MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM  ........
.NMM:....MMMMMMN. IMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO. ......
.  .++ .DMMMM$+: .....?DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM, ......`

func Fuck(c *cli.Context) error {
	who, me, err := getParameters(c)

	if err != nil {
		fmt.Println(err.Error())
		return nil
	}

	f, err := foaas.GetTheFuck(who, me)

	if err != nil {
		return err
	}

	fmt.Println(f.Message)
	fmt.Println(f.Subtitle)

	return nil
}

func getParameters(c *cli.Context) (string, string, error) {
	var who, me string

	if c.NArg() > 0 {
		w := strings.Title(c.Args()[0])
		if w == "Chuck Norris" {
			fmt.Println(Chuck)

			return "", "", errors.New("You better not try to fuck off Chuck Norris")
		}
		who = w
	} else {
		return "", "", errors.New("Missing parameter: who do you want to fuck off?")
	}

	if !c.IsSet("me") {
		m, _ := whoami()
		me = strings.Title(m)
	}

	return who, me, nil
}

func whoami() (string, error) {
	owner, err := gitconfig.GithubUser()
	if err != nil {
		owner, err = gitconfig.Username()
		if err != nil {
			return "", err
		}
	}
	return owner, nil
}
